# Generated by Django 5.1.6 on 2025-02-16 12:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='groupmember',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='groupmember',
            name='user',
        ),
        migrations.AddField(
            model_name='groupmember',
            name='user',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
