# Generated by Django 5.1.6 on 2025-02-17 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0003_alter_groupmember_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='groupmember',
            old_name='user',
            new_name='users',
        ),
    ]
